[[session]]
name = "nvim config âš™ï¸"
path = "~/.config/nvim"
startup_command = "nvim ."

[[session]]
name = "tmux config âš™ï¸"
path = "~"
startup_command = "nvim .tmux.conf"

[[session]]
name = "dotfiles"
path = "~/dotfiles/"

[[session]]
name = "home ğŸ "
path = "~"
